### ISSUE TITLE
Refresh rate issues when scaling up?

### ISSUE THREAD

**Issue by momo-the-monster** [TheThingSystem/node-pixelpusher#1]
Hey! Thanks for the awesome library. I'm using it in a sculpture right now and I've got some issues with scaling this up to a couple thousand lights running across 14 PixelPushers. I keep track of all the controllers, update their strip buffers, and then use setInterval to refresh them. I had this running smoothly doing a refresh every 60 ms or so in testing one controller, but now the best I can get is about 1 second.

Is there maybe a better way to update the controllers - can we push just the changed pixels to them instead of the whole strips, or maybe integrate some of the throttling stuff from the official PixelPusher library?

**Comment by mrose17** [comment]
hi. sorry for the delay in replying. for some reason, this issue didn't pop up on my dashboard…

i don't think the existing pixel pusher protocol allows for partial updates. i thought that the library did the basic rate adaptation algorithm, but perhaps i botched that. let me loop in heroic robotics and see what their thinking is on how we should proceed...

**Comment by jasstrong** [comment]
PixelPusher doesn't allow partial updates.  I suspect that the reason your node.js library is slow is that you must update PixelPushers in parallel with one thread for each pusher.  The design of our Java reference implementation uses a lockless data structure to achieve this.

I've actually talked with momo-the-monster by email and he's switched to using the Java library to run his sculpture.

**Comment by mrose17** [comment]
hi. thanks for the update; however, i'm not entirely convinced about the "one thread" analysis above.

sends to the network are done via non-blocking i/o.

we'd have to take a look at the node script using the package (or a stripped-down version thereof) in order to debug this properly...

**Comment by jasstrong** [comment]
I'm afraid I don't know enough js to help debug this.

**Comment by mrose17** [comment]
@jasstrong - fortunately, i know (more or less) how the node.js stuff works…

@momo-the-monster - if you want me to look into this, can you send me a minimal version of your script so i can see how you are invoking the package? if not, that's fine… thanks!

**Comment by momo-the-monster** [comment]
Sure thing. On discover, I do the following:

```
// store strip states, start black
for (var i = 0; i < numberStrips; i++) {
  controller.strips[i] = { number: i, data: new Buffer( 3 * pixelsPerStrip ) };
  controller.strips[i].data.fill( 0x00 );
}
controller.refresh(controller.strips);
```

Then I use setInterval to update the strips every x milliseconds. I had to play with this number when I started scaling up. With just one brain, I can call update every 40 ms or so. With 14 brains, I had to set it to every 250ms to avoid overloading:

```
testTimer = setInterval( function() {

        for (var key in controllers) {
          if( controllers.hasOwnProperty( key )) {
            var controller = controllers[key];
             controller.refresh( controller.strips );
          }
        }
      }, speed);
```

Note that is use hasOwnProperty becaused controllers is actually an object instead of an array.

**Comment by mrose17** [comment]
thanks. i plan to take a look this week and get back to you (and kudos for using hasOwnProperty!)

**Comment by jasstrong** [comment]
mrose17, Is your update routine trying to send all the strips, even ones that don't change?  The way it works in our java code is in the CardThread that runs a particular pusher, we extract the vector of all strips that are dirty, and then we send them in however-many-can-fit-in-a-1460-byte-datagram chunks with an UpdatePeriod pause between chunks.

This gives about a 87 Hz update.

**Comment by mrose17** [comment]
there isn't any caching/optimization… which is where i think i'll start… thanks!

**Comment by jasstrong** [comment]
It's important that you only send to pushers when data changes, because the side effect of this is that there can be more than one controlling computer in a given PixelPusher setup;  if you're only writing to group 1, then you don't affect group 2.

**Comment by mrose17** [comment]
i have published pixelpusher version 0.1.1 - please let me know if that helps, thanks!

**Comment by momo-the-monster** [comment]
Cool! I don't have access to the installation anymore (it's been boxed up
and put away) so I won't be able to test for a while. I think I'd need to
get my hands on several more pixelpushers again.

**Comment by mrose17** [comment]
no worries, i will closee the issue for now. if you have a future problem, comment on this issue or open a new one! thanks!
